spring:
  datasource:
    url: 'jdbc:postgresql://@maven.jdbc.host@:@maven.jdbc.port@/@maven.jdbc.db@'
    username: '@maven.jdbc.username@'
    password: '@maven.jdbc.password@'
  data:
    mongodb:
      url: '@maven.mongodb.url@'
  jpa:
    properties:
      hibernate:
        id: 
          new_generator_mappings: true
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: '@maven.redis.host@'
    port: '@maven.redis.port@'
    password: '@maven.redis.password@'
    database: '@maven.redis.db@'
    
logging:
  level:
#    root: WARN
    org:
      springframework:
        web: DEBUG
        hibernate: ERROR

server:
  context-path: /
  port: 9090
  tomcat:
    uri-encoding: UTF-8
    
auth:
  client: client
  secret: secret
  token: 
    name: token
    expiration: 1296000

management: 
  context-path: /admin
  security:
    enabled: true
    roles: "ROLE_ADMIN"
    
security:
#  user: 
#    name: admin
#    password: secret
#    authorities: "ROLE_ADMIN"
  oauth2:
    resource:
      filter-order: 3

cors:
  control:
    maxAge: 86400