spring:
  datasource:
    url: 'jdbc:postgresql://@maven.jdbc.host@:@maven.jdbc.port@/@maven.jdbc.db@'
    username: '@maven.jdbc.username@'
    password: '@maven.jdbc.password@'
  jpa:
    properties:
      hibernate:
        id: 
          new_generator_mappings: true
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: '@maven.redis.host@'
    port: '@maven.redis.port@'
    password: '@maven.redis.password@'
    database: '@maven.redis.db@'
  application:
    name: base-service
logging:
  level:
#    root: WARN
    org:
      springframework:
        web: DEBUG
        hibernate: ERROR

server:
  servlet: 
    context-path: /
  port: 9090
  tomcat:
    uri-encoding: UTF-8
# 尤里卡配置
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
# ribbon
ribbon:
  eureka:
    enabled: true

auth:
  client: client
  secret: secret
  token: 
    name: token
    expiration: 1296000

management: 
  security:
    enabled: true
    roles: "ACTUATOR"

security:
  oauth2:
    resource:
      filter-order: 3

cors:
  control:
    maxAge: 86400